### ISSUE TITLE
Errors encountered on Windows 10

### ISSUE THREAD

**Issue by sadranyi** [alexa/interactive-adventure-game-tool#1]
![issue](https://cloud.githubusercontent.com/assets/564700/17351263/f84e8eb2-58e1-11e6-823a-b4ea367b3d3f.png)

**Comment by rajington** [comment]
I'm not on windows so I can't test, but I feel it might be on this line [here](https://github.com/alexa/interactive-adventure-game-tool/blob/master/gulp-tasks/_upload.js#L15)

I'm wondering if it's extraneous to mention the `base` parameter, if you're willing to troubleshoot a little you can try changing the line (`interactive-adventure-game-tool/gulp-tasks/_upload.js`):

From:
```javascript
---return gulp.src('./src/skill/**/*.{js,json}', { base: "." })
```

To:
```javascript
+++return gulp.src('./src/skill/**/*.{js,json}')
```

**Comment by sadranyi** [comment]
Sure just wanted to pass it on

**Comment by rajington** [comment]
I'm guessing you probably got some errors when you ran `npm install` as well?

**Comment by sadranyi** [comment]
no everything was fine

**Comment by rjamison** [comment]
I tested things out on a Windows box and ran into the same issue.  I tried the fix suggested by @rajington and seemed to clear things up so I've pushed a commit:  edad8d998152bf310b0f5779f1a352aef5fe4110

Let me know if this clears things up for you and I'll close the issue.

**Comment by rjamison** [comment]
Closing since we haven't heard anything.  Feel free to re-open if you're continuing to have issues.
