### ISSUE TITLE
Blank window in browser

### ISSUE THREAD

**Issue by SirNeuton** [alexa/interactive-adventure-game-tool#28]
Hello guys,
after a lot of problems I finally got the tool opening a browser window (tried in Edge, Chrome and Opera) on Win10 but it seems to be only the basic scheme/design of it, without any buttons or something in it. I'm not that deeply into programming, so I have no idea what caused this and would appreciate any help I can get - Thanks in advance! (PS: just in case: I've tried to turn off AdBlock, didn't do anything)
![unbenannt](https://cloud.githubusercontent.com/assets/25620322/22708676/7cd2fe28-ed77-11e6-8414-fd8c34e95c2a.PNG)

**Comment by SirNeuton** [comment]
A complete reinstall did it for me, works like a charm now!

**Comment by wuxiaobo** [comment]
I have same problem ? reinstall  what?
