### ISSUE TITLE
Can't Get Past Second Branched Level

### ISSUE THREAD

**Issue by johnnyhamilton** [alexa/interactive-adventure-game-tool#33]
The skill works when I am at the first level (Welcome), but I encounter an error when I am at the second level (Open Door 1...). When I test it in the Service Simulator and get to the place where I am prompted to choose a door, I type in "Open Door 1". I get the following error in the Lambda request: "Unable to generate request for your skill."

I have saved and uploaded the file in the authoring tool. I have updated the Utterances and IntentSchemas into the Developer Console. 

I have also created a new branch in which I can go to the first level, but encounter the following error when I say my prompt for that level "Keep Going":
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak>My apologies, please repeat your command.<break time=\"200ms\"/>Say, “Keep going.”</speak>"
    },
    "card": {
      "text": "Please repeat your command. Say, “Keep going.”",
      "title": "Unrecognized command",
      "image": {},
      "type": "Standard"
    },
    "reprompt": {
      "outputSpeech": {
        "type": "SSML",
        "ssml": "<speak>I'm sorry.<break time=\"200ms\"/>Say, “Keep going.”</speak>"
      }
    },
    "shouldEndSession": false
  },
  "sessionAttributes": {
    "currentSceneId": 7,
    "breadcrumbs": [
      0
    ]
  }
}

**Comment by johnnyhamilton** [comment]
Here are my files from the Models folder.
[models.zip](https://github.com/alexa/interactive-adventure-game-tool/files/962229/models.zip)
Johnny

**Comment by johnnyhamilton** [comment]
I found the issue was that some of the utterances I used included capitols. When I stuck to lowercase, everything worked beautifully. I'll be publishing my skill tomorrow. 

This is a great tool. Thank you for developing it.
Johnny

**Comment by talk2camden** [comment]
Oh! Thanks! I'll have to try that!
