### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by donHolmberg** [alexa/interactive-adventure-game-tool#4]
nam start gives this error....

5 verbose stack Error: missing script: start

**Comment by rjamison** [comment]
Sorry you're having trouble.  That error usually indicates the "package.json" file for project is missing a "start" element inside "scripts", though this project's seems fine:  

````
"scripts": {
    "postinstall": "node node_modules/jspm/jspm.js install",
    "start": "node node_modules/gulp/bin/gulp.js"
},
````

What command are you running to produce the error, and what directory are you running it from?

**Comment by donHolmberg** [comment]
Thanks, 

I figured it out, I just had to switch to the directory where everything was installed.

Thanks,
Don
