### ISSUE TITLE
Alexa Skill Kit does not work in US West (oregon) only US East (N. Virginia)

### ISSUE THREAD

**Issue by jamestichenor** [alexa/interactive-adventure-game-tool#5]
I could not set the Alexa skill kit to my Lamda with it set to the US West, found some documentation on the Alexa Skill Kit site that I should set it to US East (N. Virginia).. 

this is a detail related to your setup instructions.

**Comment by rjamison** [comment]
Thanks for the feedback, updated the README in regards.

Closed with 5f42308
