### ISSUE TITLE
HTTP error 404 Not Found

### ISSUE THREAD

**Issue by codeALLthealgorithms** [alexa/interactive-adventure-game-tool#56]
Does anyone know why I'm getting this error? I'm trying to run this on Windows.

npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> node-sass@3.13.1 install C:\Users\Shree\interactive-adventure-game-tool\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\Shree\interactive-adventure-game-tool\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Shree\interactive-adventure-game-tool\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Shree\interactive-adventure-game-tool\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Shree\interactive-adventure-game-tool\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Shree\interactive-adventure-game-tool\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shree\\interactive-adventure-game-tool\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Shree\interactive-adventure-game-tool\node_modules\node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN interactive-adventure-game-tool@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shree\AppData\Roaming\npm-cache\_logs\2017-11-21T17_24_57_347Z-debug.log

**Comment by jas7229** [comment]
Just installed on Windows last weekend and definitely ran into the same problem...to be honest I ended up trying up a bunch of things and can't really recall what I did in the end to fix it. Wish I had taken notes.

Think it might help to try installing node-sass separately though (which also might involve installing python and visual studio) and see if that helps?

**Comment by codeALLthealgorithms** [comment]
I ended up giving up and installing it on my Mac, which worked somehow. Thanks anyways!
