### ISSUE TITLE
Missing files when I run 

### ISSUE THREAD

**Issue by shockrock** [alexa/interactive-adventure-game-tool#6]
I've reinstalled a couple of times and I don't see any errors cloning from git or when doing npm install but when I run the following file is missing. There is actually no jspm_packages directory.
400 GET http://localhost:9000/jspm_packages/system.js 

I do have other node applications installed on the mac so I don't know if there is a conflict.
My other application runs on a different port. The page does load, it is just black.

Any help or ideas would be appreciated. I'm excited to try this new tool. Thanks!

**Comment by rjamison** [comment]
Definitely an issue when running "npm install".  Perhaps you're using an older version of Node or NPM?  Here's the environment we are testing with:

````
$ npm -version
3.8.6
$ node -v
v6.1.0
````

**Comment by TonyAMZN** [comment]
Thanks for creating this issue.

There is a missing step in the "Setup Your Machine" section:
After you install Node.js, but before you run 'npm install', run the following command:
````
npm install jspm -g
````
Once this is done, you should be able to continue with the instructions as presented. I will close this issue once I have updated the README.

**Comment by rob94p** [comment]
i am also having this issue :  

```
/Users/Rob/Documents/workspace/Alexa/interactive-adventure-game-tool/node_modules/jspm/lib/common.js:116
    throw 'Error parsing package.json file ' + file;
    ^
Error parsing package.json file /Users/Rob/.jspm/config
```

**Comment by xiangxie** [comment]
This sounds like a install corruption case. What I suggest is try jspm install -f first. If this not work, probably reinstall jspm.
